# -*- coding: utf-8 -*-
"""XAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNzlR0PDKOU2X3hqPw0VD5TxKwCfg-mf

Explainable AI by Leonie Leeuwis s1138789
"""

from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import sklearn.ensemble
import lime
from lime import lime_tabular
import shap
import eli5
import matplotlib.pyplot as plt
np.random.seed(1)

data = pd.read_csv("heart.csv")
print(data.head())

X = data.drop('target', axis=1)
y = data['target']

train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(X, y, train_size=0.80, test_size=0.20)

# Handling missing values
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
train_imputed = imp_mean.fit_transform(train)

# Handling missing values
test_imputed = imp_mean.transform(test)

# Train a random forest
rf = sklearn.ensemble.RandomForestClassifier(n_estimators=1000, random_state=42)
rf.fit(train_imputed, labels_train)

predictions = rf.predict(test_imputed)
accuracy = accuracy_score(labels_test, predictions)
print("Accuracy:", accuracy)

#Lime explanations

# Generates the explanation
categorical_features = [X.columns.get_loc(col) for col in ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']]
lime_explainer = lime.lime_tabular.LimeTabularExplainer(train_imputed,
                                                   feature_names=X.columns,
                                                   class_names=['no_heartdisease', 'heartdisease'],
                                                   categorical_features=categorical_features,
                                                   verbose=True,
                                                   mode='classification')

i = 0
exp1 = lime_explainer.explain_instance(test_imputed[i], rf.predict_proba, num_features=5)

exp1.show_in_notebook(show_all=True)

# Coefficients of the local model
exp1.as_list()

# Commented out IPython magic to ensure Python compatibility.
# alternative way to plot
# %matplotlib inline
fig = exp1.as_pyplot_figure()

# LIME's Faithfulness (with feature masking)

i = 0
top_feature_idx_lime = exp1.local_exp[1][0][0]

copy_patient_lime = test_imputed[i].copy()
prob_orig = rf.predict_proba(copy_patient_lime.reshape(1, -1))[0][1]

# Masking with mean
copy_patient_lime[top_feature_idx_lime] = train_imputed[:, top_feature_idx_lime].mean()
prob_new_lime = rf.predict_proba(copy_patient_lime.reshape(1, -1))[0][1]

print(f"LIME Top Feature Index: {top_feature_idx_lime}")
print(f"LIME Faithfulness Drop: {prob_orig - prob_new_lime:.4f}")

#Lime stability

i = 0

# explanation of the same patient twice
lime_exp_1 = lime_explainer.explain_instance(
    test_imputed[i],
    rf.predict_proba,
    num_features=len(X.columns)
)

lime_exp_2 = lime_explainer.explain_instance(
    test_imputed[i],
    rf.predict_proba,
    num_features=len(X.columns)
)

def lime_to_vector(exp, n_features):
    vec = np.zeros(n_features)
    for feature_idx, weight in exp.local_exp[1]:
        vec[feature_idx] = weight

    return vec

# make vectors
vec1 = lime_to_vector(lime_exp_1, len(X.columns))
vec2 = lime_to_vector(lime_exp_2, len(X.columns))

# stability score
lime_diff = np.mean(np.abs(vec1 - vec2))

print("LIME explanation 1:", vec1)
print("LIME explanation 2:", vec2)
print("LIME stability:", lime_diff)

#Lime completeness
lime_exp = lime_explainer.explain_instance(
    test_imputed[i],
    rf.predict_proba,
    num_features=len(X.columns)
)


lime_weight_sum = sum(weight for _, weight in lime_exp.local_exp[1])


lime_reconstructed = lime_exp.intercept[1] + lime_weight_sum


prediction = rf.predict_proba(test_imputed[i].reshape(1, -1))[0][1]

# completeness error
lime_completeness = abs(prediction - lime_reconstructed)

print("LIME reconstructed prediction:", lime_reconstructed)
print("LIME completeness error:", lime_completeness)

# SHAP explanations
shap_explainer = shap.KernelExplainer(rf.predict_proba, shap.kmeans(train_imputed, 10))
nb_points_explain = round(0.2*train.shape[0])
shap_values = shap_explainer(train.iloc[0:nb_points_explain, :])

ref = shap_explainer.expected_value
print("Average predicted output: ",ref)

# Waterfall plot for a single explanation
i = 0
shap.plots.waterfall(shap_values[0, :, 1])

# SHAP Faithfulness (Top feature masking)
import numpy as np

i = 0
shap_vec = shap_values.values[i, :, 1]
top_feature_idx_shap = np.argmax(np.abs(shap_vec))
top_feature_name_shap = X.columns[top_feature_idx_shap]

copy_patient_shap = test_imputed[i].copy()


prob_orig = rf.predict_proba(copy_patient_shap.reshape(1, -1))[0][1]

# Mask the top feature
copy_patient_shap[top_feature_idx_shap] = train_imputed[:, top_feature_idx_shap].mean()

# Get new prediction probability
prob_new_shap = rf.predict_proba(copy_patient_shap.reshape(1, -1))[0][1]

print(f"SHAP Top Feature: {top_feature_name_shap}")
print(f"Original Probability: {prob_orig:.4f}")
print(f"New Probability: {prob_new_shap:.4f}")
print(f"diff: {prob_orig - prob_new_shap:.4f}")

#SHAP stability
i = 0

#same instance twice
shap_values_1 = shap_explainer.shap_values(test_imputed[i].reshape(1, -1))
shap_values_2 = shap_explainer.shap_values(test_imputed[i].reshape(1, -1))

#vectors
vec1 = np.array(shap_values_1[0, :, 1])
vec2 = np.array(shap_values_2[0, :, 1])

# difference
shap_diff = np.mean(np.abs(vec1 - vec2))

print("SHAP explanation 1:", vec1)
print("SHAP explanation 2:", vec2)
print("SHAP stability difference:", shap_diff)
print("Lower = more stable")

#SHAP completeness
shap_values = shap_explainer.shap_values(test_imputed[i].reshape(1, -1))


if isinstance(shap_values, list):
    shap_vec = np.array(shap_values[1][0])
    base_value = shap_explainer.expected_value[1]
else:
    shap_vec = np.array(shap_values[0])
    base_value = shap_explainer.expected_value

# reconstruct prediction
shap_reconstructed = base_value + np.sum(shap_vec)

# completeness error
shap_completeness = abs(prediction - shap_reconstructed)

print("SHAP reconstructed prediction:", shap_reconstructed)
print("SHAP completeness error:", shap_completeness)

#Eli5 explanation

patient_data = test_imputed[0]

eli5.show_prediction(rf, patient_data,
                     feature_names=X.columns.tolist(),
                     show_feature_values=True)

# ELI5 Faithfulness (Top feature masking)
import eli5


exp_eli5 = eli5.explain_prediction(rf, test_imputed[0], feature_names=X.columns.tolist())

#top feature
top_feature_name_eli5 = exp_eli5.targets[0].feature_weights.pos[0].feature
if top_feature_name_eli5 == '<BIAS>':
    top_feature_name_eli5 = exp_eli5.targets[0].feature_weights.pos[1].feature

top_feature_idx_eli5 = X.columns.get_loc(top_feature_name_eli5)

#diff
copy_patient_eli5 = test_imputed[0].copy()
prob_orig = rf.predict_proba(copy_patient_eli5.reshape(1, -1))[0][1]

# Mask with mean
copy_patient_eli5[top_feature_idx_eli5] = train_imputed[:, top_feature_idx_eli5].mean()
prob_new_eli5 = rf.predict_proba(copy_patient_eli5.reshape(1, -1))[0][1]

print(f"ELI5 Top Feature: {top_feature_name_eli5} (Index: {top_feature_idx_eli5})")
print(f"Original Probability: {prob_orig:.4f}")
print(f"New Probability: {prob_new_eli5:.4f}")
print(f"diff: {prob_orig - prob_new_eli5:.4f}")

#Stability ELI5

i = 0

exp_eli5_1 = eli5.explain_prediction(
    rf,
    test_imputed[i],
    feature_names=X.columns.tolist()
)

exp_eli5_2 = eli5.explain_prediction(
    rf,
    test_imputed[i],
    feature_names=X.columns.tolist()
)

def eli5_to_vector(exp, feature_names):

    vec = np.zeros(len(feature_names))

    weights = exp.targets[0].feature_weights.pos + exp.targets[0].feature_weights.neg

    for w in weights:
        if w.feature in feature_names:
            idx = feature_names.index(w.feature)
            vec[idx] = w.weight

    return vec

vec1 = eli5_to_vector(exp_eli5_1, X.columns.tolist())
vec2 = eli5_to_vector(exp_eli5_2, X.columns.tolist())

eli5_diff = np.mean(np.abs(vec1 - vec2))

print("ELI5 stability difference:", eli5_diff)
print("Lower = more stable")

#Eli5 completeness
exp_eli5 = eli5.explain_prediction(
    rf,
    test_imputed[i],
    feature_names=X.columns.tolist()
)

# positive and negative weights
weights = exp_eli5.targets[0].feature_weights.pos + exp_eli5.targets[0].feature_weights.neg

eli5_sum = 0
eli5_bias = 0

for w in weights:
    if w.feature == '<BIAS>':
        eli5_bias = w.weight
    elif w.feature in X.columns.tolist():
        eli5_sum += w.weight

eli5_reconstructed = eli5_bias + eli5_sum

eli5_completeness = abs(prediction - eli5_reconstructed)

print("ELI5 reconstructed prediction:", eli5_reconstructed)
print("ELI5 completeness error:", eli5_completeness)

#Plot Faithfullness

abs_drop_lime = abs(prob_orig - prob_new_lime)
abs_drop_shap = abs(prob_orig - prob_new_shap)
abs_drop_eli5 = abs(prob_orig - prob_new_eli5)

abs_drops = [abs_drop_lime, abs_drop_shap, abs_drop_eli5]
methods = ['LIME', 'SHAP', 'ELI5']

plt.figure(figsize=(10, 6))
colors = ['#ff9999','#66b3ff','#99ff99']
bars = plt.bar(methods, abs_drops, color=colors)

plt.title('Comparison of Absolute Faithfulness Drops (Higher = More Impact)', fontsize=14)
plt.ylabel('Absolute Change in Prediction Probability', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.005, round(yval, 4), ha='center', fontweight='bold')

plt.show()

print(f"Absolute LIME Drop: {abs_drop_lime:.4f}")
print(f"Absolute SHAP Drop: {abs_drop_shap:.4f}")
print(f"Absolute ELI5 Drop: {abs_drop_eli5:.4f}")

#plot Stability

# stability scores
methods = ['LIME', 'SHAP', 'ELI5']
stability_scores = [lime_diff, shap_diff, eli5_diff]


plt.figure(figsize=(8,5))
bars = plt.bar(methods, stability_scores)

plt.title("Stability Comparison of Explanation Methods")
plt.ylabel("Explanation Difference (lower = more stable)")
plt.xlabel("Method")

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             height,
             round(height,4),
             ha='center',
             va='bottom')

plt.show()

#Plot Completeness
methods = ['LIME', 'SHAP', 'ELI5']
scores = [lime_completeness, shap_completeness[1], eli5_completeness]

plt.figure(figsize=(8,5))
bars = plt.bar(methods, scores)

plt.title("Completeness Comparison")
plt.ylabel("Completeness Error (lower = better)")
plt.xlabel("Method")

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        round(height, 4),
        ha='center',
        va='bottom'
    )

plt.show()